# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
mod_id=galena_hats
mod_name=Galena Hats
mod_author=Team Galena
mod_version=<mc>-0.0.0-dev

# Common
mc_version=26.1.2

# Neoforge
neoforge_version=26.1.2.76

# Fabric
fabric_api_version=0.152.1+26.1.2
fabric_loader_version=0.19.3

#Dependencies
freecam_neoforge_version=dBYtlwgX
freecam_fabric_version=dvyNrVvc
cloth_config_fabric_version=GFM8zh9J

# Publishing
maven_group=dev.galena
repository=teamgalena/hats
modrinth_project_id=y8aeirnj
