# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
mod_id=galena_hats
mod_name=Galena Hats
mod_author=Team Galena
mod_version=1.21.1-0.0.0-dev

# Common
mc_version=1.21.1

# Neoforge
neoforge_version=21.1.152

# Fabric
fabric_api_version=0.115.1+1.21.1
fabric_loader_version=0.16.10

#Dependencies
mixin_extras_version=0.4.1
gson_version=2.10
logback_version=1.4.14
freecam_neoforge_version=ROfcbxxe
freecam_fabric_version=Cg10zLnR
cloth_config_fabric_version=HpMb5wGb

# Publishing
maven_group=dev.galena
repository=teamgalena/hats
modrinth_project_id=y8aeirnj